databases/gdbm
databases/memcached
databases/postgresql16-client
databases/postgresql16-contrib
devel/autoconf
devel/bison
devel/git-tiny
devel/gmake
devel/libffi
devel/ncurses
devel/patch
devel/rbenv
devel/readline
devel/ruby-build
lang/gcc
lang/rust
security/openssl31
shells/bash
textproc/libyaml
